name: Pull Request Build

on:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      host: ubuntu-22.04
      images: core-image-base core-image-weston core-image-x11 amlogic-image-headless-initrd amlogic-image-headless-sd amlogic-image-sato
      machines: amlogic-p200 amlogic-p212 amlogic-s400 friendlyelec-nanopik2 hardkernel-odroidc2 hardkernel-odroidc4 hardkernel-odroidhc4 hardkernel-odroidn2 hardkernel-odroidn2plus khadas-vim2 khadas-vim3 khadas-vim3l libretech-ac libretech-cc radxa-zero seirobotics-sei510 seirobotics-sei610 
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      branch: ${{github.base_ref}}
      url: ${{github.server_url}}/${{github.repository}}
    secrets:
      TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}
